version: '3.8'

services:
  webhook-bridge:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "${PORT:-3000}:3000"
    environment:
      - PORT=3000
      - DEFAULT_MATTERMOST_WEBHOOK_URL=${DEFAULT_MATTERMOST_WEBHOOK_URL}
      - LOG_LEVEL=${LOG_LEVEL:-info}
      - LOG_PAYLOADS=${LOG_PAYLOADS:-false}
      - REQUEST_TIMEOUT=${REQUEST_TIMEOUT:-10000}
      - NODE_ENV=production
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 5s