name = "mattermost-bridges"
compatibility_date = "2024-03-01"
main = "src/main.ts"

# Enhanced logging (requires Enterprise plan)
# logpush = true

# Development configuration
[env.development]
name = "mattermost-bridges-dev"

[env.staging]
name = "mattermost-bridges-staging"

[env.production]
name = "mattermost-bridges-prod"

# Environment variables (set via wrangler secret put)
# MATTERMOST_WEBHOOK_URL = "your-default-webhook-url-here"

# Custom domain configuration (optional)
# [[env.production.routes]]
# pattern = "bridges.yourdomain.com/*"

# Rate limiting (optional)
# [limits]
# cpu_time = 50

# Observability settings
[observability]
enabled = true